### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by nodiscc** [jatekos101/20euros#1]
Hi, nice project. Would you like to add a Free Software license for your game? Currently the only licensing text is 

> Feel free to fork my version and make pull requests!

I can recommend the MIT, AGPL or WTFPL licenses.
http://choosealicense.com/licenses/ and https://tldrlegal.com/licenses/browse may help you.

**Comment by IBPX** [comment]
Yes. Without a license, you can't really legally fork it and do stuff.

I'd recommend MIT or CC0.

**Comment by Kickball** [comment]
@jatekos101 will this issue be looked into?

**Comment by nodiscc** [comment]
Unmaintained project
